# Build Docker image, push to ACR, then deploy to AKS via Helm

trigger: none

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '9dea1af3-11b8-4ab8-aef2-fd1f562515f7'
  imageRepository: 'lgexample654'
  containerRegistry: 'lgexample654.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'


  # AKS / Helm
  aksResourceGroup: 'terraform-dev'
  aksClusterName: 'demo-aks'
  helmReleaseName: 'lg-python-example'
  helmChartPath: 'helm/python-app'

  # Agent
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

# ============================
# DEPLOY STAGE
# ============================
- stage: DeployToAKS
  displayName: Deploy Helm to AKS
  dependsOn: Build
  jobs:
  - job: HelmDeploy
    displayName: Helm deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Deploy Helm Chart to AKS
      inputs:
        azureSubscription: 'Azure subscription 1(1)(525c7c1f-f5e9-4bf4-8d7a-5b7a06889a12)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -e
          
          echo "Getting AKS credentials..."
          az aks get-credentials \
            --resource-group $(aksResourceGroup) \
            --name $(aksClusterName) \
            --overwrite-existing
          
          echo "Deploying Helm chart..."
          helm upgrade --install $(helmReleaseName) \
            $(System.DefaultWorkingDirectory)/$(helmChartPath) \
            --set image.repository=$(containerRegistry)/$(imageRepository) \
            --set image.tag=$(tag) \
            --wait
          
          echo "Waiting for rollout..."
          kubectl rollout status deployment/$(helmReleaseName)

